### PR TITLE
Overhaul HMC and HMC tuning implementation

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by oschulz** [comment]
@cescalara wanna give this version a whirl?

**Comment by cescalara** [comment]
Sure! When trying to install I run into a dependency conflict with ChainRules, Zygote and ChainRulesCore. Any advice?

```
pkg> add https://github.com/bat/BAT.jl.git#hmc-tuning
    Updating git-repo `https://github.com/bat/BAT.jl.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ChainRules [082447d4]:
 ChainRules [082447d4] log:
 ├─possible versions are: 0.0.1-0.7.49 or uninstalled
 ├─restricted by compatibility requirements with Zygote [e88e6eb3] to versions: 0.7.34-0.7.49
 │ └─Zygote [e88e6eb3] log:
 │   ├─possible versions are: 0.1.0-0.6.3 or uninstalled
 │   └─restricted to versions 0.6 by BAT [c0cd4b16], leaving only versions 0.6.0-0.6.3
 │     └─BAT [c0cd4b16] log:
 │       ├─possible versions are: 2.0.0 or uninstalled
 │       └─BAT [c0cd4b16] is fixed to version 2.0.0
 └─restricted by compatibility requirements with ChainRulesCore [d360d2e6] to versions: 0.0.1 or uninstalled — no versions left
   └─ChainRulesCore [d360d2e6] log:
     ├─possible versions are: 0.10.2 or uninstalled
     ├─restricted to versions 0.9.44-0.10 by ForwardDiffPullbacks [450a3b6d], leaving only versions 0.10.2
     │ └─ForwardDiffPullbacks [450a3b6d] log:
     │   ├─possible versions are: 0.1.3 or uninstalled
     │   └─ForwardDiffPullbacks [450a3b6d] is fixed to version 0.1.3
     └─ChainRulesCore [d360d2e6] is fixed to version 0.10.2
```

**Comment by oschulz** [comment]
> Sure! When trying to install I run into a dependency conflict with ChainRules, Zygote and ChainRulesCore. Any advice?

That's weird, because GitHub CI does run. Did you try a package update first? If that doesn't work, can you send me you Project.toml and Manifest.toml?

**Comment by cescalara** [comment]
Indeed, I also tried to copy the versions used in the CI to no avail. Package update didn't make any difference. Could be something to do with how I am managing packages? Not sure on the best practices here. 

Here are the files (.txt is just to get GitHub to accept)
[Project.toml.txt](https://github.com/bat/BAT.jl/files/6622684/Project.toml.txt)
[Manifest.toml.txt](https://github.com/bat/BAT.jl/files/6622685/Manifest.toml.txt)

**Comment by cescalara** [comment]
Hi, from a quick look using the default settings the adaptation looks good. I'm still finding my way around the new code. How does the user control the warmup length now, is it through MCMCBurnIn?

Also, for the simple gaussian example I am running with many trials, the fit randomly fails with:
```

BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/multi_cycle_burnin.jl:86
┌ Info: Initializing new RNG of type Random123.Philox4x{UInt64, 10}
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/algotypes/bat_default.jl:44
┌ Info: Using transform algorithm DensityIdentityTransform()
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/algotypes/bat_default.jl:44
┌ Info: Trying to generate 4 viable MCMC chain(s).
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/chain_pool_init.jl:56
┌ Info: Selected 4 MCMC chain(s).
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/chain_pool_init.jl:174
┌ Info: Begin tuning of 4 MCMC chain(s).
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/multi_cycle_burnin.jl:38
Excessive output truncated after 524320 bytes.┌ Info: MCMC Tuning cycle 1 finished, 4 chains, 3 tuned, 4 converged.
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/multi_cycle_burnin.jl:69
┌ Info: MCMC Tuning cycle 2 finished, 4 chains, 4 tuned, 4 converged.
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/multi_cycle_burnin.jl:69
┌ Info: MCMC tuning of 4 chains successful after 2 cycle(s).
└ @ BAT /Users/fran/.julia/packages/BAT/592rR/src/samplers/mcmc/multi_cycle_burnin.jl:75
MCMC tuning of 4 chains aborted after 4 cycle(s).

Stacktrace:
  [1] mcmc_burnin!(outputs::Nothing, tuners::Vector{BAT.AHMCTuner{AdvancedHMC.Adaptation.StanHMCAdaptor{AdvancedHMC.Adaptation.WelfordVar{Float64, Vector{Float64}}, AdvancedHMC.Adaptation.NesterovDualAveraging{Float64}}}}, chains::Vector{BAT.AHMCIterator{HamiltonianMC{BAT.DiagEuclideanMetric, BAT.LeapfrogIntegrator, BAT.NUTS, BAT.StanHMCTuning}, PosteriorDensity{BAT.ReshapedDensity{BAT.DensityWithShape{BAT.GenericDensity{var"#1#2"{input_data}}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, ArrayShape{Real, 1}}, BAT.DistributionDensity{ValueShapes.UnshapedNTD{NamedTupleDist{(:mu,), Tuple{Normal{Float64}}, Tuple{ValueAccessor{ScalarShape{Real}}}}}, BAT.HyperRectBounds{Float64}}, BAT.HyperRectBounds{Float64}, ArrayShape{Real, 1}}, Random123.Philox4x{UInt64, 10}, BAT.RNGPartition{Random123.Philox4x{UInt64, 10}, Tuple{UInt64, UInt64}, NTuple{6, UInt32}, UnitRange{Int64}}, StructArrays.StructVector{DensitySample{Vector{Float64}, Float64, Float64, BAT.AHMCSampleID, Nothing}, NamedTuple{(:v, :logd, :weight, :info, :aux), Tuple{ArrayOfSimilarArrays{Float64, 1, 1, 2, ElasticArrays.ElasticMatrix{Float64, 1, Vector{Float64}}}, Vector{Float64}, Vector{Float64}, StructArrays.StructVector{BAT.AHMCSampleID, NamedTuple{(:chainid, :chaincycle, :stepno, :sampletype, :hamiltonian_energy, :tree_depth, :divergent, :step_size), Tuple{Vector{Int32}, Vector{Int32}, Vector{Int64}, Vector{Int32}, Vector{Float64}, Vector{Int32}, Vector{Bool}, Vector{Float64}}}, Int64}, Vector{Nothing}}}, CartesianIndex{1}}, AdvancedHMC.Hamiltonian{AdvancedHMC.DiagEuclideanMetric{Float64, Vector{Float64}}, BAT.LogDensityOf{PosteriorDensity{BAT.ReshapedDensity{BAT.DensityWithShape{BAT.GenericDensity{var"#1#2"{input_data}}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, ArrayShape{Real, 1}}, BAT.DistributionDensity{ValueShapes.UnshapedNTD{NamedTupleDist{(:mu,), Tuple{Normal{Float64}}, Tuple{ValueAccessor{ScalarShape{Real}}}}}, BAT.HyperRectBounds{Float64}}, BAT.HyperRectBounds{Float64}, ArrayShape{Real, 1}}}, BAT.GradFunc{BAT.LogDensityOf{PosteriorDensity{BAT.ReshapedDensity{BAT.DensityWithShape{BAT.GenericDensity{var"#1#2"{input_data}}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, ArrayShape{Real, 1}}, BAT.DistributionDensity{ValueShapes.UnshapedNTD{NamedTupleDist{(:mu,), Tuple{Normal{Float64}}, Tuple{ValueAccessor{ScalarShape{Real}}}}}, BAT.HyperRectBounds{Float64}}, BAT.HyperRectBounds{Float64}, ArrayShape{Real, 1}}}, BAT.LogDensityOf{PosteriorDensity{BAT.ReshapedDensity{BAT.DensityWithShape{BAT.GenericDensity{var"#1#2"{input_data}}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, ArrayShape{Real, 1}}, BAT.DistributionDensity{ValueShapes.UnshapedNTD{NamedTupleDist{(:mu,), Tuple{Normal{Float64}}, Tuple{ValueAccessor{ScalarShape{Real}}}}}, BAT.HyperRectBounds{Float64}}, BAT.HyperRectBounds{Float64}, ArrayShape{Real, 1}}}, ArrayShape{Real, 1}, ArrayShape{Real, 1}, ForwardDiffAD}}, AdvancedHMC.Transition{AdvancedHMC.PhasePoint{Vector{Float64}, AdvancedHMC.DualValue{Float64, Vector{Float64}}}, NamedTuple{(:n_steps, :is_accept, :acceptance_rate, :log_density, :hamiltonian_energy, :hamiltonian_energy_error, :max_hamiltonian_energy_error, :tree_depth, :numerical_error, :step_size, :nom_step_size), Tuple{Int64, Bool, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Float64, Float64}}}, AdvancedHMC.NUTS{AdvancedHMC.MultinomialTS, AdvancedHMC.ClassicNoUTurn, AdvancedHMC.Leapfrog{Float64}, Float64}}}, burnin_alg::MCMCMultiCycleBurnin, convergence_test::BrooksGelmanConvergence, strict_mode::Bool, nonzero_weights::Bool, callback::typeof(BAT.nop_func))
    @ BAT ~/.julia/packages/BAT/592rR/src/samplers/mcmc/multi_cycle_burnin.jl:79
  [2] bat_sample_impl(rng::Random123.Philox4x{UInt64, 10}, target::PosteriorDensity{BAT.DensityWithShape{BAT.GenericDensity{var"#1#2"{input_data}}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, BAT.DistributionDensity{NamedTupleDist{(:mu,), Tuple{Normal{Float64}}, Tuple{ValueAccessor{ScalarShape{Real}}}}, BAT.HyperRectBounds{Float64}}, BAT.HyperRectBounds{Float64}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, algorithm::MCMCSampling{HamiltonianMC{BAT.DiagEuclideanMetric, BAT.LeapfrogIntegrator, BAT.NUTS, BAT.StanHMCTuning}, NoDensityTransform, MCMCChainPoolInit, MCMCMultiCycleBurnin, BrooksGelmanConvergence, typeof(BAT.nop_func)})
    @ BAT ~/.julia/packages/BAT/592rR/src/samplers/mcmc/mcmc_sample.jl:67
  [3] #bat_sample#164
    @ ~/.julia/packages/BAT/592rR/src/algotypes/sampling_algorithm.jl:45 [inlined]
  [4] bat_sample
    @ ~/.julia/packages/BAT/592rR/src/algotypes/sampling_algorithm.jl:45 [inlined]
  [5] #bat_sample#166
    @ ~/.julia/packages/BAT/592rR/src/algotypes/sampling_algorithm.jl:59 [inlined]
  [6] bat_sample(target::PosteriorDensity{BAT.DensityWithShape{BAT.GenericDensity{var"#1#2"{input_data}}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, BAT.DistributionDensity{NamedTupleDist{(:mu,), Tuple{Normal{Float64}}, Tuple{ValueAccessor{ScalarShape{Real}}}}, BAT.HyperRectBounds{Float64}}, BAT.HyperRectBounds{Float64}, NamedTupleShape{(:mu,), Tuple{ValueAccessor{ScalarShape{Real}}}}}, algorithm::MCMCSampling{HamiltonianMC{BAT.DiagEuclideanMetric, BAT.LeapfrogIntegrator, BAT.NUTS, BAT.StanHMCTuning}, NoDensityTransform, MCMCChainPoolInit, MCMCMultiCycleBurnin, BrooksGelmanConvergence, typeof(BAT.nop_func)})
    @ BAT ~/.julia/packages/BAT/592rR/src/algotypes/sampling_algorithm.jl:58
  [7] macro expansion
    @ ./timing.jl:287 [inlined]
  [8] top-level scope
    @ ./In[44]:10
  [9] eval
    @ ./boot.jl:360 [inlined]
 [10] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1094

```
that I can't make much sense of. Happy to share the code.

**Comment by oschulz** [comment]
> does the user control the warmup length now, is it through MCMCBurnIn

Yes, it's coupled to the burn-in cycle length now. Longer term, we should find a way for the tuner to suggest to the burn-in how many samples should be generated next.

**Comment by oschulz** [comment]
> 4 chains successful after 2 cycle(s). [...] MCMC tuning of 4 chains aborted after 4 cycle(s).

Well that should *not* happen! :-)

**Comment by oschulz** [comment]
Yes, please, share the code

**Comment by cescalara** [comment]
```julia
# Simulation
N = 100
mu = 0.0
sigma = 1.0

# Sampling
iters = 2000
chains = 4

# Benchmarking
Ntrials = 1000;
Here's the code:
# Data
mutable struct input_data
    N::Int64
    mu::Float64
    sigma::Float64
    y::Array{Float64, 1}
end
output = rand(Normal(mu, sigma), N)
data = input_data(N, mu, sigma, output)
```

```julia
# Model
function likelihood(data) 
    
    params -> begin
        
        ll_value = sum(logpdf.(Normal(params.mu, data.sigma), data.y))
        
        return LogDVal(ll_value)
    end
end

prior = NamedTupleDist(
    mu = Normal(0.0, 50.0)
);

posterior = PosteriorDensity(likelihood(data), prior);
```

```julia
# Run Ntrials sims and fits
exec_time = Array{Float64}(undef, Ntrials)
sample_mean = Array{Float64}(undef, Ntrials)
neff = Array{Float64}(undef, Ntrials)
step_size = Array{Float64}(undef, (chains, Ntrials))
tree_depth = Array{Float64}(undef, (chains * iters));

for n in 1:Ntrials
    data.y = rand(Normal(data.mu, data.sigma), data.N)
    posterior = PosteriorDensity(likelihood(data), prior);
    exec_time[n] = @elapsed out = bat_sample(posterior, 
        MCMCSampling(mcalg=HamiltonianMC(), nsteps=iters, nchains=4, 
            trafo=NoDensityTransform()))
    s = out.result
    c = out.generator
    sample_mean[n] = mean(unshaped.(s))[1]
    neff[n] = bat_eff_sample_size(unshaped.(s)).result[1]
    for j in 1:chains
        start = ((j-1) * iters) + 1 
        step_size[j,n] = c.chains[j].transition.stat.step_size
        tree_depth = s.info.tree_depth
    end
end
```

**Comment by oschulz** [comment]
> Here's the code

Runs through now with more forgiving convergence criterion.

**Pull request merged**
