### PR TITLE
Integration distribution rtols

### PR DESCRIPTION
**Pull request by sthayashi**

### CODE REVIEW

**Comment by oschulz** [comment]
This will need an update to resolve the conflicts

**Comment by sthayashi** [comment]
Does this mean another commit push? It doesn't actually show me the details of the conflict; only that a conflict exists.

**Comment by oschulz** [comment]
You'll need to do this offline on your system, probably. Update your local master branch, then try to merge this branch with master and use `git mergetool` or so to fix the conflict. There's lots of documentation around on this kind of stuff. :-)

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
