### PR TITLE
Bugfix for importance samplers

### PR DESCRIPTION
**Pull request by Cornelius-G**
use `logvalof_unchecked` instead of `logvalof`

### CODE REVIEW

**Comment by oschulz** [comment]
Samplers should use `logvalof`, not `logvalof_unchecked` - the latter is only for code that implements a density, not for code that uses it. `logvalof_unchecked` will return nonsense for out-of-bounds values with truncated densities, for example.

**Comment by Cornelius-G** [comment]
Hm, the problem was that with `logvalof` I got errors and could not run the sampling, with `logvalof_unchecked` it seems to work.
For a simple example like this:
```
likelihood = params -> begin
    r = logpdf.(Normal(2.0, 1.5), params.a)
    return LogDVal(r)
end

prior = BAT.NamedTupleDist(
    a = -10..10
)

posterior = PosteriorDensity(likelihood, prior);
samples, chains = bat_sample(posterior, (10^5, 4), SobolSampler());
```
I get this error:
```
Density evaluation failed at v = [0.0] due to exception MethodError(ValueShapes.unshaped, ((a = 0.0,),), 0x0000000000006b97), density has type BAT.TruncatedDensity{PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}},BAT.HyperRectBounds{Float64},Int64}
density_logval_type at abstract_density.jl:312 [inlined]
density_logval_type at abstract_density.jl:312 [inlined]
(::BAT.var"#kw##logvalof")(::NamedTuple{(:use_bounds, :strict),Tuple{Bool,Bool}}, ::typeof(logvalof), ::PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}}, ::NamedTuple{(:a,),Tuple{Float64}}) at none:0
logvalof_unchecked(::PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}}, ::NamedTuple{(:a,),Tuple{Float64}}) at posterior_density.jl:67
logvalof_unchecked(::BAT.TruncatedDensity{PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}},BAT.HyperRectBounds{Float64},Int64}, ::NamedTuple{(:a,),Tuple{Float64}}) at truncated_density.jl:30
#logvalof#24(::Bool, ::Bool, ::typeof(logvalof), ::BAT.TruncatedDensity{PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}},BAT.HyperRectBounds{Float64},Int64}, ::Array{Float64,1}, ::Type{Float64}) at abstract_density.jl:153
logvalof at abstract_density.jl:144 [inlined]
logvalof at abstract_density.jl:144 [inlined]
_broadcast_getindex_evalf at broadcast.jl:630 [inlined]
_broadcast_getindex at broadcast.jl:603 [inlined]
getindex at broadcast.jl:563 [inlined]
macro expansion at broadcast.jl:909 [inlined]
macro expansion at simdloop.jl:77 [inlined]
copyto! at broadcast.jl:908 [inlined]
copyto! at broadcast.jl:863 [inlined]
copy at broadcast.jl:839 [inlined]
materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(logvalof),Tuple{Base.RefValue{BAT.TruncatedDensity{PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}},BAT.HyperRectBounds{Float64},Int64}},Array{Array{Float64,1},1}}}) at broadcast.jl:819
bat_sample_impl(::Random123.Philox4x{UInt64,10}, ::PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}}, ::Tuple{Int64,Int64}, ::SobolSampler) at importance_sampler.jl:49
#bat_sample#61 at sampling_algorithm.jl:108 [inlined]
bat_sample at sampling_algorithm.jl:108 [inlined]
#bat_sample#63 at sampling_algorithm.jl:122 [inlined]
bat_sample(::PosteriorDensity{BAT.GenericDensity{var"#17#18"},BAT.DistributionDensity{ValueShapes.NamedTupleDist{(:a,),Tuple{Uniform{Float64}},Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}},BAT.HyperRectBounds{Float64}},BAT.HyperRectBounds{Float64},ValueShapes.NamedTupleShape{(:a,),Tuple{ValueShapes.ValueAccessor{ValueShapes.ScalarShape{Real}}}}}, ::Tuple{Int64,Int64}, ::SobolSampler) at sampling_algorithm.jl:121
top-level scope at output_examples.jl:50

```

**Comment by oschulz** [comment]
That should be fixable, I'll take a look.

**Comment by oschulz** [comment]
Should be fixed not (9165263), can you test?

**Comment by Cornelius-G** [comment]
> Should be fixed now ([9165263](https://github.com/bat/BAT.jl/commit/916526377f321f279a217be9ca1597e9755c1412)), can you test?

Yes, this works. Thanks!

**Pull request closed without merging**
