### PR TITLE
[WIP] Include gaussian shell

### PR DESCRIPTION
**Pull request by sthayashi**

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks! Can you deal with the test failures?

**Comment by sthayashi** [comment]
I think the missing dependency for `SpecialFunctions.jl` is only used for its `gamma` function in gaussian_shell.jl. Can I add this into the `Project.toml`?

**Comment by oschulz** [comment]
Of course, SpecialFunctions is already an indirect dependency anyway. Put it in with a version bound of "0.10".

**Comment by oschulz** [comment]
Almost there - just listing `BAT.GaussianShell` in the docs is still missing. You can add it to "experimental_api.md" for now.

Hint: You'll have a faster turn-around time if you run tests and docs-gen (see "docs/make.jl") locally before pushing and having Travis run it.

**Pull request merged**
