### PR TITLE
Add flat index support for bat_marginalize()

### PR DESCRIPTION
**Pull request by Micki-D**
Adds support for doing 

marg_s = BAT.bat_marginalize(some_shaped_samples, i)

where `i` is an Integer, Vector or Tuple of Integers or Unit Range.

The new marginalized samples will have `N` ScalarShaped parameters with the keys being encoded according to the keys of the input data. `N` being the number of columns selected in the marginalization process.

If a range is input, Expressions corresponding to the selected columns will be generated up to a range of 5. For larger ranges strings will be used to create the encoded symbols to save memory.

### CODE REVIEW

**Comment by oschulz** [comment]
@Cornelius-G can you give this a test?

**Comment by oschulz** [comment]
@Cornelius-G, let me know when you're done checking this out?

**Comment by Cornelius-G** [comment]
@oschulz I did now check this with our examples and the flat indexing seems to work again! 
So from my side, this would be ready to be merged. Thanks @Micki-D

**Comment by oschulz** [comment]
Thanks @Micki-D and @Cornelius-G !

**Pull request merged**
