### PR TITLE
extended test coverage for log_uniform.jl

### PR DESCRIPTION
**Pull request by Micki-D**
I assumed the definition in line 33 of the src file:

LogUniform() = LogUniform{Float64}(0, 1)

 is supposed to catch an empty input as an arg error since the first arg of LogUniform needs to be finite per definition.

### CODE REVIEW

**Comment by oschulz** [comment]
> `LogUniform() = LogUniform{Float64}(0, 1)` is supposed to catch an empty input

Ooops, no, it's not, it's just supposed to be a default ctor. Better change it to  `LogUniform() = LogUniform{Float64}(1, 2)`.

**Comment by Micki-D** [comment]
Okeydoke, I changed the default ctor definition aswell as the test for it. 
The test will error though, since the master branch still has the old definition

**Comment by oschulz** [comment]
> The test will error though, since the master branch still has the old definition

Just include the change in this PR.

**Comment by Micki-D** [comment]
Yeah it already is

**Comment by oschulz** [comment]
Nice!

**Pull request merged**
