### PR TITLE
Bias correction and trim function replacement (Addressing issue #97)

### PR DESCRIPTION
**Pull request by VasylHafych**

### CODE REVIEW

**Comment by oschulz** [comment]
You need to fix docs generation (need to add `BAT.integrate_hyperrectangle_cov`, etc. to "docs/src/internal_api.md", please keep that file sorted).

Underscore functions like `BAT._trim` shouldn't have docstrings - if they are worth documenting, maybe better rename them to a non-underscore name (but not just `trim`).

**Comment by VasylHafych** [comment]
Hi Oliver! The issue with docs is fixed, I have also fixed threshold value f_min/f_max equal to 500, as we used it in the paper.

**Comment by oschulz** [comment]
Is this ready to be merged?

**Comment by VasylHafych** [comment]
Give me one more day to test it, since we've made quite a few changes!

**Comment by oschulz** [comment]
Sure - please rebase/update to the current master branch as well, there's an important fix in there to prevent test failures due to HDF5/Blosc/Compat version conflicts.

**Comment by VasylHafych** [comment]
Hi Oliver! I have tested changes — working correctly. You can merge it now (it is updated to the current master branch).

**Pull request merged**
