### PR TITLE
Fix bug in plotting of 1D samples

### PR DESCRIPTION
**Pull request by Cornelius-G**

### CODE REVIEW

**Comment by oschulz** [comment]
@Cornelius-G, could you check why the docs-generation fails?

**Comment by Cornelius-G** [comment]
@oschulz I have no idea why the docs fail again. It were only minor changes that should not affect the docu. However, the error message is `ERROR: LoadError: ArgumentError: Package Documenter [e30172f5-a6a5-5a46-863b-614d45cd2de4] is required but does not seem to be installed:` So it seems there is a problem when Travis is setting up the environment. Is it possible to just retry building the docs?

**Comment by Cornelius-G** [comment]
Ok, it seems it automatically restarted and now passed.

**Comment by oschulz** [comment]
I ran it again - looks like it was just a temporary failure. Sorry, should have checked first.

**Pull request merged**
