### PR TITLE
[WIP] Small changes to fix any problems with implemented distributions

### PR DESCRIPTION
**Pull request by sthayashi**
…atistics package instead of Distributions package

### CODE REVIEW

**Comment by sthayashi** [comment]
I noticed this somewhat irregular problem when integrating the funnel distribution
```
funnel = BAT.FunnelDistribution();
bsample = bat_sample(funnel, 10^5).result;
```
Sometimes the below occurs:
```
julia> bat_integrate(bsample).result
┌ Info: Using integration algorithm AHMIntegration{CholeskyPartialWhitening,GeyerAutocorLen}
│   whitening: CholeskyPartialWhitening CholeskyPartialWhitening()
│   autocorlen: GeyerAutocorLen GeyerAutocorLen()
│   volumetype: Symbol HyperRectangle
│   max_startingIDs: Int64 10000
│   max_startingIDs_fraction: Float64 2.5
│   rect_increase: Float64 0.1
│   warning_minstartingids: Int64 16
│   dotrimming: Bool true
└   uncertainty: Array{Symbol}((1,))
[ Info: Harmonic Mean Integration started. Samples in dataset 1 / 2: 	50000 / 49999	Parameters:	3
[ Info: Data Whitening.
[ Info: Apply Whitening Transformation to Data Set 2
[ Info: Create Space Partitioning Tree
[ Info: Determine Hyperrectangle Starting Samples
┌ Warning: Returned minimum number of starting points: 16
└ @ BAT ~/.julia/dev/BAT/src/integration/ahmi/hyper_rectangle.jl:104
┌ Warning: Returned minimum number of starting points: 16
└ @ BAT ~/.julia/dev/BAT/src/integration/ahmi/hyper_rectangle.jl:104
[ Info: Determine Tolerances for Hyperrectangle Creation
[ Info: Create 33 Hyperrectangles using 1 thread(s)
```
Which I think means it's having problems finding centers of the hyperrectangles. I'm not sure how serious of an issue this is. I think there was some sort of problem with the funnel distribution, but I'm not sure if this is still a problem, or exactly what the details were.

**Comment by sthayashi** [comment]
- [ ] gaussian_shell.jl is not currently included in the master branch's distributions.jl. My version has it included, so maybe this was intentional?

- [ ] Add tests for specifically for the distributions, not just integration of the distributions. Will the HierarchicalDistribution method of covariance be removed, and thus not need tests?

**Comment by oschulz** [comment]
> gaussian_shell.jl is not currently included in the master branch's distributions.jl

That's a mistake, could you to a separate PR to fix it?

**Comment by oschulz** [comment]
> Will the HierarchicalDistribution method of covariance be removed, and thus not need tests

Yes, these empirical "get cov for a distribution by samling" implementations are workarounds, they will hopefully be removed soon.

**Pull request merged**
