### PR TITLE
Added test for bridge sampling, corrected error in bridge sampler

### PR DESCRIPTION
**Pull request by celaue**
Hi @oschulz,

I made some changes to the bridge sampling estimator: Correct error in the integral estimate; added mode of non-convergences
Furthermore, this PR includes test cases for the integrator.

Cedrik

### CODE REVIEW

**Comment by oschulz** [comment]
Let me have a look at the test failures (likely unrelated) before I merge.

**Comment by oschulz** [comment]
Unrelated test failures should be fixed now, can you merge with, resp. rebase on, master?

**Comment by celaue** [comment]
What do you mean by " can you merge with, resp. rebase on, master"

**Comment by oschulz** [comment]
> What do you mean by " can you merge with, resp. rebase on, master"

I mean either merge the current master branch in, or rebase your PR branch on top of it.

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
