### PR TITLE
[WIP] AHMC type stability fixes

### PR DESCRIPTION
**Pull request by sthayashi**

### CODE REVIEW

**Comment by sthayashi** [comment]
This pull request is for fixing the type stability problems in the AHMC portion of code.

Sources of known type instability from `AHMCIterator`

- [ ] `AHMCMetric` https://github.com/bat/BAT.jl/blob/b7b348590ae91e0d0bf52144b294f5765afa44b9/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L94
- [ ] `AHMCIntegrator` https://github.com/bat/BAT.jl/blob/b7b348590ae91e0d0bf52144b294f5765afa44b9/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L104
- [ ] `AHMCAdaptor` https://github.com/bat/BAT.jl/blob/b7b348590ae91e0d0bf52144b294f5765afa44b9/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L107
- [ ] `AHMCProposal` https://github.com/bat/BAT.jl/blob/b7b348590ae91e0d0bf52144b294f5765afa44b9/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L106
- [ ] hamiltonian and transition https://github.com/bat/BAT.jl/blob/b7b348590ae91e0d0bf52144b294f5765afa44b9/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L100-L101

**Comment by oschulz** [comment]
Is this still WIP?

**Comment by sthayashi** [comment]
Yes, still working on this PR. I found a source of type instability `AHMCiterator`, and I'm trying to figure out an elegant solution to it.
https://github.com/bat/BAT.jl/blob/cbbc5cffde137aa2fa1c79562b31deba8ba71a97/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L94 `AHMCMetric` can return three different types of euclidean metrics depending on the `algorithm.metric` property. This results in a type instability, because the function can return a union of three different euclidean metrics.
From what I understand, `AHMCMetric` is acting as an intermediary between BAT and `AdvancedHMC`. Would it be better/possible to store `AdvancedHMC`'s metric in the algorithm without this function `AHMCMetric` between them?

**Comment by sthayashi** [comment]
`BAT.HMCMetric` can return three different metrics from `AdvancedHMC` though.
```
julia> AdvancedHMC.AbstractMetric |> subtypes
3-element Vector{Any}:
 AdvancedHMC.DenseEuclideanMetric
 AdvancedHMC.DiagEuclideanMetric
 AdvancedHMC.UnitEuclideanMetric
```
`@code_warntype BAT.AHMCIterator(rng, mcalg, density, info, x_init)` tells me that are two sources of instability.

The first one

```Base.getproperty(algorithm, :metric)::BAT.HMCMetric``` 

I should be coming from `algorithm.metric` https://github.com/bat/BAT.jl/blob/b7b348590ae91e0d0bf52144b294f5765afa44b9/src/samplers/mcmc/ahmc/ahmc_sampler.jl#L94

and the variable `metric` itself is type unstable

```metric::Union{AdvancedHMC.UnitEuclideanMetric{Float64, Tuple{Int64}}, AdvancedHMC.DenseEuclideanMetric{Float64, Vector{Float64}, Matrix{Float64}, UpperTriangular{Float64, Matrix{Float64}}}, AdvancedHMC.DiagEuclideanMetric{Float64, Vector{Float64}}}```

**Comment by oschulz** [comment]
Indeed, `HamiltonianMC` needs to get type parameters for all of it's fields.

**Comment by oschulz** [comment]
This will need some changes after #295 is merged (had to do that to improve HMC tuning).

**Comment by oschulz** [comment]
> Would it be preferable to start a new PR once #295 has been merged?

Whatever is easier for you.

**Pull request closed without merging**
